# action.yml
name: "Kitchen Terraform"
description: "Run kitchen commands"
branding:
  icon: "arrow-left"
  color: "black"
inputs:
  kitchen-command: # id of input
    description: "The command to run for example: help"
    required: true
    default: "help"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.kitchen-command }}
